### PR TITLE
Homework 8 (Soap UI)

### PR DESCRIPTION
**Pull request by Katsiaryna-Ledak**

### CODE REVIEW

**Comment by NataliaTikhomirova** [comment]
1) it's better to make separate pr for each hw (I see commits for hw7 in this mr)
2) test CheckCorrectSuggestionTest fails with null pointer exception for me
3) setUp and tearDown - there are 2 sections in each test with similar names, no need to create such scripts by yourself, you can copy the script to the proper section and program run it at the proper moment
4) asserts - it's better to make more sense asserts for text what you want to check (not only status, smth NOT contains, schema, tags, all these tests can run successfully, but the word can be different and it will be a bug)
please add tests for word
5) DDT test 
there are "if then" cases with data in the script. Please, rewrite it for data from file, because if it'll be 100 cases for such script it would work. For example, you can write 5 rows with data.
6) No logit difference of test cases by suits

**Comment by Katsiaryna-Ledak** [comment]
> 1. it's better to make separate pr for each hw (I see commits for hw7 in this mr)
> 2. test CheckCorrectSuggestionTest fails with null pointer exception for me
> 3. setUp and tearDown - there are 2 sections in each test with similar names, no need to create such scripts by yourself, you can copy the script to the proper section and program run it at the proper moment
> 4. asserts - it's better to make more sense asserts for text what you want to check (not only status, smth NOT contains, schema, tags, all these tests can run successfully, but the word can be different and it will be a bug)
>    please add tests for word
> 5. DDT test
>    there are "if then" cases with data in the script. Please, rewrite it for data from file, because if it'll be 100 cases for such script it would work. For example, you can write 5 rows with data.
> 6. No logit difference of test cases by suits

Hello, Natalia, thanks for the review!
1. That happened, because I didn't make a rebase after HW7, cause it's still in progress. I will create new project with new PR for the next HW.
2. I've made some changes in new commit
3. I've deleted these sections in new commit
4. Added Assertion to correct the word in IgnoreCapitalCaseTest
5. I've removed "if" sections and added array with data
6. Divided project into test suites.

Will be waiting for your review.

**Comment by NataliaTikhomirova** [comment]
4. asserts 
I saw that you added logic assert in the first test, but this is all.
In the second test, the expected word is different than the actual but the test is green and you don't check it at all. 
Maybe you choose the wrong case? 
Please add logic asserts of expected words

**Comment by Katsiaryna-Ledak** [comment]
> 1. asserts
>    I saw that you added logic assert in the first test, but this is all.
>    In the second test, the expected word is different than the actual but the test is green and you don't check it at all.
>    Maybe you choose the wrong case?
>    Please add logic asserts of expected words

Hello, Natalia!
I've added a logic test in a new commit [d4fc0ed](https://github.com/Katsiaryna-Ledak/Ekaterina_Khudzhamkulova/commit/d4fc0ed693e915510b7f3b4adf5f7fc8390eccc9)

**Pull request merged**
